---
- name: Deploy Telegram Bot BadmintonCourtAgent to your Server
  hosts: localhost
  vars:
    base: lookup('env', 'BASE_DIRECTORY')
  tasks:
    - name: Create logs folder
      file:
        path: "{{ base }}/logs"
    - name: Create Telegram Bot Conf File
      copy:
        dest: "{{ base }}/.telegram-bot-conf"
        content: |
          [bot]
          token={{ lookup('env', 'TELEGRAM_BOT_TOKEN') }}
    - name: Log in to DockerHub
      docker_login:
        username: {{ lookup('env', 'DOCKERHUB_USERNAME') }}
        password: {{ lookup('env', 'DOCKERHUB_TOKEN') }}
    - name: Run BadmintonCourtAgent Bot in a Container
      docker_container:
        name: badminton_court_agent_bot
        image: flyotlin/badminton-court-agent:polling
        volumes:
          - "{{ base }}/logs:/app/logs"
          - "{{ base }}/db:/app/db"
